[tool.poetry]
name = "ai_openchat"
version = "1.1.7"
description = 'Python module for asynchronous interaction with OpenAI'
authors = ["Whitev2"]
license = "MIT License"
readme = "README.md"
homepage = "https://github.com/Whitev2/async-openai"
repository = "https://github.com/Whitev2/async-openai"
keywords = ["python", "async", "python3", "async_chat_gpt", "openai", "chatGPT", "aiohttp"]
classifiers = [
        'License :: OSI Approved :: Apache Software License',
        'Operating System :: OS Independent',
        'Intended Audience :: End Users/Desktop',
        'Intended Audience :: Developers',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.10',
        'Programming Language :: Python :: 3.11',
        'Programming Language :: Python :: Implementation :: PyPy',
        'Programming Language :: Python :: Implementation :: CPython',
]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/Whitev2/async-openai/issues"

[tool.poetry.dependencies]
python = "^3.8"
aiohttp = "^3.8.3"

[tool.poetry.dev-dependencies]


[tool.black]
line-length = 80
target-version = ['py37', 'py38']
exclude = '''
(
    \.eggs
  | \.git
  | \.tox
  | build
  | dist
  | venv
)
'''

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 80
